[package]
name = "nes"
version = "0.1.0"
authors = ["Ben <ben.godin@hotmail.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.4.3"
